### ISSUE TITLE
SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by MarketingPip** [TranscribeJs/transcribe.js#9]
In enviroments with improper headers 

```
Uncaught ReferenceError: SharedArrayBuffer is not defined
    at FileTranscriber._createModule (shout.wasm_no-simd.js:8:4085)
    at FileTranscriber.init (Transcriber.js:144:30)
    at FileTranscriber.init (FileTranscriber.js:127:17)
```

```html
    import { simd } from "https://cdn.jsdelivr.net/gh/TranscribeJs/transcribe.js@2.0.3/examples/lib/simd.js";
import createModule from "https://cdn.jsdelivr.net/gh/TranscribeJs/transcribe.js@2.0.3/src/shout/shout.wasm_no-simd.js";
import { FileTranscriber } from "https://cdn.jsdelivr.net/gh/TranscribeJs/transcribe.js@2.0.3/src/index.js";

// create new instance
const transcriber = new FileTranscriber({
  createModule,
  model: "https://cdn.jsdelivr.net/gh/TranscribeJs/transcribe.js@2.0.3/examples/models/ggml-tiny-q5_1.bin", // path to ggml model file
});

// init wasm transcriber worker
await transcriber.init();

// transcribe audio/video file
const result = await transcriber.transcribe("https://cdn.jsdelivr.net/gh/TranscribeJs/transcribe.js@2.0.3/examples/jfk.wav");

console.log(result)
```

**Comment by thurti** [comment]
Does your browser **and** webserver meet the [requirements](https://github.com/TranscribeJs/transcribe.js?tab=readme-ov-file#prerequisite)?

**Comment by MarketingPip** [comment]
@thurti - I guess it does not (I was using this in codepen iframe so that explains it) - is there any way we can bypass this?

**Comment by thurti** [comment]
No, this cannot be bypassed. The headers are part of the [security requirements](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements) for using SharedArrayBuffer.

**Comment by MarketingPip** [comment]
@thurti - so this can be bypassed by using crossOrigin attribute but I am still getting Memory issues. Am I using wrong build or doing something wrong?

```html
<script type="module" crossorigin="anonymous">
      import { simd } from "https://cdn.jsdelivr.net/gh/TranscribeJs/transcribe.js@master/examples/lib/simd.js";
import { default as createModuleNoSimd } from "https://cdn.jsdelivr.net/gh/TranscribeJs/transcribe.js@master/src/shout/shout.wasm_no-simd.js";
  
  
import { FileTranscriber } from "https://cdn.jsdelivr.net/gh/TranscribeJs/transcribe.js@master/src/index.js";

 //
// helper file to preload/cache model file

// install service worker
if ("serviceWorker" in navigator) {
 
}

// fetch model file after confirm
async function preload(modelFile, printConsole) {
  if (
    await window.confirm(
      "Transcribe.js needs a model file to work. This file is 32MB and will be cached in your browser. Click OK to load the file."
    )
  ) {
    printConsole("Downloading model file... please wait.");
    await fetch(modelFile);
    printConsole("Model file downloaded. You can now start transcribing.");
    return true;
  } else {
    printConsole(
      "Model file not downloaded. You need to load the model file before you can start transcribing."
    );
    return false;
  }
}

// check if model file is cached, if not, preload
// change cache name to update model file in cache
async function preloadModel(modelFile, printConsole = console.log) {
  await preload(modelFile, printConsole)
}
 (async function () {
        // feature detect simd support
        // only if you need to support browsers/devices without simd support
        const createModule = (await simd())
          ? false
          : createModuleNoSimd;

        // Preload model
        const path = location.pathname.replace(/\/[^/]+$/, "");
        const modelFile = "https://cdn.jsdelivr.net/gh/TranscribeJs/transcribe.js@2.0.3/examples/models/ggml-tiny-q5_1.bin"

        preloadModel(modelFile, printConsole).then(( ) => {
           
           
          document.querySelector(".start").removeAttribute("disabled");
            document.querySelector(".cancel").removeAttribute("disabled");
            document.querySelector(".preload-model").style.display = "none";
         
        });

        // Console output
        const consoleOutput = document.querySelector(".console");

        function printConsole(msg) {
          consoleOutput.innerText += msg + "\n";
          consoleOutput.scrollTop = consoleOutput.scrollHeight;
        }

        // New Transcriber
        const transcriber = new FileTranscriber({
          createModule,

          model: modelFile,

          print: printConsole,
          printErr: printConsole,

          onReady: () => {
            console.log("Ready to transcribe.");
          },

          onProgress: (progress) => {
            console.log("Progress", progress);
          },

          onCanceled: () => {
            console.log("Canceled");
          },

          onComplete: () => {
            console.log("Transcription complete.");
          },
        });

        // transcribe audio file
        async function transcript() {
          try {
            await transcriber.init();

            const result = await transcriber.transcribe("https://cdn.jsdelivr.net/gh/TranscribeJs/transcribe.js@2.0.3/examples/jfk.wav", {
              lang: "en",
            });

            console.log(result);

            document.querySelector(".result").innerText = "";

            result.transcription.forEach((segment) => {
              document.querySelector(".result").innerText +=
                segment.text + "\n";
            });
          } catch (error) {
            console.error("Error transcribing", error);
          }
        }

        // Button events
        document.querySelector(".start").addEventListener("click", async () => {
          document.querySelector(".result").innerHTML =
            "<em>processing...</em>";
          transcript();
        });

        document
          .querySelector(".cancel")
          .addEventListener("click", async () => {
            transcriber.cancel();
          });

        document
          .querySelector(".preload-model")
          .addEventListener("click", async (e) => {
            await preloadModel(modelFile, printConsole).then((loaded) => {
              if (loaded) {
                document.querySelector(".start").removeAttribute("disabled");
                document.querySelector(".cancel").removeAttribute("disabled");
                document.querySelector(".preload-model").style.display = "none";
              }
            });
          });
      })();
</script>
```

**Comment by thurti** [comment]
> so this can be bypassed by using crossOrigin attribute

See my previous answer.
> No, this cannot be bypassed. The headers are part of the [security requirements](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements) for using SharedArrayBuffer.

The jsdelivr cdn doesn't set these headers, so you will end up with `SharedArrayBuffer is not defined` error.

The solution is to host the files yourself and set the correct headers in your web server config.

**Comment by thurti** [comment]
Could you please provide more details so I can reproduce the error.
- browser + version
- os + version
- error message
- example code to reproduce this error

**Comment by MarketingPip** [comment]
@thurti the code in last input is producing the issue...

**Comment by thurti** [comment]
I'm sorry, but I don't think that I can help you with that.

**Comment by MarketingPip** [comment]
@thurti - ah I am stupid. I missed your last part in previous comment where you indicate the headers would be set based on CDN.
